[package]
name = "effective-flock"
version = "0.1.1"
edition = "2024"

[dependencies]
tokio = { version = "1.41.2", features = ["full"] }
tokio-postgres = { version = "0.7.13", features = [] }
rocksdb = "0.23"
rand = "0.9.1"
